# Generated by Django 2.0.3 on 2018-03-21 05:55

import datetime
from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Individual_Responsible', models.CharField(choices=[('Stanley Njoku', 'Stanley Njoku'), ('Beverly Everhart', 'Beverly Everhart'), ('Lenka Barrettova', 'Lenka Barrettova'), ('Chris Bradshaw', 'Chris Bradshaw'), ('Connie Gordon', 'Connie Gordon'), ('Kevin Tennyson', 'Kevin Tennyson')], max_length=150)),
                ('agency', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Safety', 'Safety'), ('Environment', 'Environment'), ('Fee', ' Fee'), ('Regulatory', 'Regulatory'), ('Report', 'Report')], max_length=150)),
                ('Type', models.CharField(choices=[('County', 'County'), ('Local', 'Local'), ('State', 'State'), ('Federal', 'Federal'), ('EPA', 'EPA'), ('OSHA', 'OSHA')], max_length=150)),
                ('start_Date', models.DateField(default=datetime.datetime.today)),
                ('due_Date', models.DateField(default=management.models.Compliance.due_Date)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('On Hold', 'On Hold'), ('Approved', 'Approved')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Manifest_Tracking_Number', models.CharField(max_length=200)),
                ('Building_Address', models.CharField(max_length=200)),
                ('Vendor_Name', models.CharField(choices=[('Clean Harbors', 'Clean Harbors'), ('Ingenium', 'Ingenium'), ('Veolia', 'Veolia')], max_length=150)),
                ('EPA_ID_Location', models.CharField(choices=[('B2500 - CAL000342024', 'B2500 - CAL000342024'), ('B6000 - CAD983606872', 'B6000 - CAD983606872'), ('4000  - CAD981991276', '4000  - CAD981991276'), ('B2000 - CAD983606872', 'B2000 - CAD983606872'), ('B925  - CAR000158816', 'B925  - CAR000158816'), ('B3110 - CAD981453871', 'B3110 - CAD981453871'), ('B487 - CAL000248918', 'B487 - CAL000248918'), ('B5731 - CAL000346207', 'B5731 - CAL000346207'), ('B5500 - CAL000095938', 'B5500 - CAL000095938'), ('Select One', 'Select One')], default='Select One', max_length=100)),
                ('Type', models.CharField(choices=[('Weekly Shipment', 'Weekly Shipment'), ('Monthly Shipment', 'Monthly Shipment'), ('90-day Shipment', '90-day Shipment'), ('180-day/270-day Shipment', '180-day/270-day Shipment'), ('Urgent Shipment', 'Urgent Shipment')], max_length=150)),
                ('category', models.CharField(choices=[('Drum Shipment', 'Drum Shipment'), ('Labpack', 'Labpack'), ('Bulk Shipment', 'Bulk Shipment')], max_length=150)),
                ('Weight_Shipped', models.CharField(max_length=150)),
                ('weight_Unit', models.CharField(choices=[('Gallons (Liquid Only)', 'Gallons (Liquid Only)'), ('Kilograms', 'Kilograms'), ('Liters Liquid Only', 'Liters Liquid Only'), ('Metric Tons', 'Metric Tons'), ('Cubic Meter', 'Cubic Meter'), ('Pounds', 'Pounds'), ('Tons', 'Tons'), ('Cubic Yards', 'Cubic Yards'), ('Select One', 'Select One')], default='Select One', max_length=150)),
                ('Date_Generator_Sgned', models.DateField(default=management.models.Manifest.due_Date)),
                ('Date_to_DTSC', models.DateField(default=management.models.Manifest.due_Date)),
                ('Manifest_Return_from_Vendor', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=150)),
                ('Manifest_Signatory', models.CharField(choices=[('Stanley Njoku', 'Stanley Njoku'), ('Beverly Everhart', 'Beverly Everhart'), ('Lenka Barrettova', 'Lenka Barrettova'), ('Chris Bradshaw', 'Chris Bradshaw'), ('Connie Gordon', 'Connie Gordon'), ('Kevin Tennyson', 'Kevin Tennyson')], max_length=150)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('On Hold', 'On Hold'), ('Approved', 'Approved')], max_length=150)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_Responsible', models.CharField(choices=[('Stanley Njoku', 'Stanley Njoku'), ('Beverly Everhart', 'Beverly Everhart'), ('Lenka Barrettova', 'Lenka Barrettova'), ('Chris Bradshaw', 'Chris Bradshaw'), ('Connie Gordon', 'Connie Gordon'), ('Kevin Tennyson', 'Kevin Tennyson')], max_length=150)),
                ('category', models.CharField(choices=[('Safety', 'Safety'), ('Environment', 'Environment'), ('Fee', ' Fee'), ('Regulatory', 'Regulatory'), ('Report', 'Report')], max_length=150)),
                ('Type', models.CharField(choices=[('Hazardous Waste Management', 'Hazardous Waste Management'), ('Confined Space', 'Confined Space'), ('Emergency Response Management', ' Emergency Response Management'), ('Storm Water', 'Storm Water'), ('Hazardous Management Business Plan', 'Hazardous Management Business Plan'), ('Respiratory Fit Testing', 'Respiratory Fit Testing'), ('Worker Compensation', 'Worker Compensation'), ('Ergonomics', 'Ergonomics'), ('Respiratory Fit Testing', 'Respiratory Fit Testing'), ('Job Hazard Analysis', 'Job Hazard Analysis'), ('Lockout/tagout Procedures', 'Lockout/tagout Procedures'), ('Machine Safety', 'Machine Safety'), ('Chemical Hazard Communication', 'Chemical Hazard Communication'), ('Accident Prevention Programs', 'Accident Prevention Programs')], max_length=150)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('On Hold', 'On Hold'), ('Approved', 'Approved')], max_length=150)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('estimated_completion', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
