# Generated by Django 2.0.1 on 2018-03-03 08:01

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='due_Date',
            field=models.DateField(default=management.models.Compliance.due_Date),
        ),
    ]
