# Generated by Django 2.0.1 on 2018-03-04 10:21

import datetime
from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20180304_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='due_Date',
            field=models.DateField(default=management.models.Compliance.due_Date),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='Date_Generator_Sgned',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
