# Generated by Django 2.0.1 on 2018-03-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sustainable_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Recorded_By', models.CharField(max_length=50)),
                ('account_No', models.CharField(max_length=70)),
                ('building', models.CharField(choices=[('3110 Regatta Bvld', '3110 Regatta Bvld'), ('2500 Atlas Rd', '2500 Atlas Rd'), ('6000 James Watson Dr', '6000 6000 James Watson Dr'), ('4000', '4000'), ('2000', '2000'), ('800', '800'), ('825', '825'), ('875', '875'), ('925', '925'), ('1000', '1000'), ('225', '225'), ('235', '235'), ('245', '245'), ('255', '255'), ('265', '265'), ('800', '800'), ('825', '825'), ('875', '875'), ('925', '925'), ('5731', '5731'), ('487', '487'), ('5400', '5400'), ('5500', '5500')], max_length=100)),
                ('city', models.CharField(choices=[('Hercules', 'Hercules'), ('Richmond', 'Richmond'), ('Santa Rosa', 'Santa Rosa'), ('Pleasanton', 'Pleasanton'), ('Benicia', 'Benicia')], max_length=100)),
                ('region', models.CharField(choices=[('NorCal', 'NorCal'), ('NorWest', 'NorWest'), ('APAC', 'APAC'), ('Europe', 'Europe')], max_length=100)),
                ('type', models.CharField(choices=[('Electricity', 'Electricity'), ('Gas', 'Gas'), ('Therms', 'Therms'), ('Water', 'Water')], max_length=100)),
                ('Amount_Consumped', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('kWh', 'kWh'), ('Therms', 'Therms'), ('Gallons', 'Gallons')], max_length=100)),
                ('Billing_Period_Start_Date', models.DateField()),
                ('Billing_Period_End_Date', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
