# Generated by Django 2.0.1 on 2018-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainable_report',
            name='Amount_Spent',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
