# Generated by Django 2.0.1 on 2018-03-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0002_sustainable_report_amount_spent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sustainable_report',
            old_name='type',
            new_name='Type',
        ),
        migrations.AddField(
            model_name='sustainable_report',
            name='category',
            field=models.CharField(choices=[('Monthly Statement', 'Monthly Statement'), ('Quarterly Statement', 'Quarterly Statement'), ('Annual Statement', 'Annual Statement')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sustainable_report',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('On Hold', 'On Hold'), ('Approved', 'Approved')], default=2, max_length=150),
            preserve_default=False,
        ),
    ]
