# Generated by Django 2.0.1 on 2018-03-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0003_auto_20180303_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainable_report',
            name='building',
            field=models.CharField(choices=[('3110 Regatta Bvld', '3110 Regatta Bvld'), ('2500 Atlas Rd', '2500 Atlas Rd'), ('6000 James Watson Dr', '6000 James Watson Dr'), ('4000', '4000'), ('2000', '2000'), ('800', '800'), ('825', '825'), ('875', '875'), ('925', '925'), ('1000', '1000'), ('225', '225'), ('235', '235'), ('245', '245'), ('255', '255'), ('265', '265'), ('800', '800'), ('825', '825'), ('875', '875'), ('925', '925'), ('5731', '5731'), ('487', '487'), ('5400', '5400'), ('5500', '5500')], max_length=100),
        ),
    ]
