# Generated by Django 2.0.3 on 2018-03-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceMatric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Name', models.CharField(max_length=300)),
                ('Type', models.CharField(choices=[('Document/Program Review', 'Document/Program Review'), ('Report Submission', 'Report Submission'), ('Inspection', 'Inspection'), ('Fee', 'Fee'), ('Training', 'Training'), ('Permit/License/Registration RenewalTD ', 'Permit/License/Registration RenewalTD ')], max_length=1)),
                ('fee', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1)),
                ('category', models.CharField(choices=[('Regulatory', 'Regulatory'), ('Non-Regulatory', 'Non-Regulatory')], max_length=50)),
                ('Record_Location', models.CharField(max_length=300)),
                ('Submittal_Required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Enforcement_Agency', models.CharField(max_length=300)),
                ('building_Number', models.CharField(choices=[('3110', '3110'), ('2500', '2500'), ('6000', '6000'), ('4000', '4000'), ('2000', '2000'), ('800', '800'), ('825', '825'), ('875', '875'), ('925', '925'), ('1000', '1000'), ('225', '225'), ('235', '235'), ('245', '245'), ('255', '255'), ('265', '265'), ('800', '800'), ('825', '825'), ('875', '875'), ('925', '925'), ('5731', '5731'), ('487', '487'), ('5400', '5400'), ('5500', '5500')], max_length=50)),
                ('Task', models.TextField()),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual'), ('Bienniel', 'Bienniel'), ('Trienniel', 'Trienniel'), ('Every 5 Years', 'Every 5 Years'), ('Quadrennial', 'Quadrennial'), ('Quinquennial', 'Quinquennial')], max_length=60)),
                ('EHS_Person', models.CharField(choices=[('Doug Fleming', 'Doug Fleming'), ('Lenka Barrettova', 'Lenka Barrettova'), ('Chris Bradshaw', 'Chris Bradshaw'), ('Connie Gordon', 'Connie Gordon'), ('Stanley Njoku', 'Stanley Njoku'), ('Beverly Everhart', 'Beverly Everhart'), ('Kevin Tennyson', 'Kevin Tennyson'), ('Mark Kessler', 'Mark Kessler'), ('Kimberly Jones', 'Kimberly Jones'), ('Jo Schneider', 'Jo Schneider')], max_length=300)),
                ('building', models.CharField(choices=[('3110 Regatta', '3110 Regatta'), ('2500 Atlas', '2500 Atlas'), ('6000 James Watson', '6000 James Watson'), ('4000 Alfred Nobel', '4000 Alfred Nobel'), ('2000 Alfred Nobel', '2000 Alfred Nobel'), ('800 Alfred Nobel', '800 Alfred Nobel'), ('825 Alfred Nobel', '825 Alfred Nobel'), ('875 Alfred Nobel', '875 Alfred Nobel'), ('925 Alfred Nobel', '925 Alfred Nobel'), ('1000 Alfred Nobel', '1000 Alfred Nobel'), ('225 Linus Pauling', '225 Linus Pauling'), ('235 Linus Pauling', '235 Linus Pauling'), ('245 Linus Pauling', '245 Linus Pauling'), ('255 Linus Pauling', '255 Linus Pauling'), ('265 Linus Pauling', '265 Linus Pauling'), ('5731 W. Las Positas', '5731 W. Las Positas'), ('487 Aviation Boulevard', '487 Aviation Boulevard'), ('5400 E. 2nd St', '5400 E. 2nd St'), ('5500 E. 2nd St', '5500 E. 2nd St')], max_length=50)),
                ('contact_Person', models.CharField(max_length=300)),
                ('due_Date', models.DateField(null=True)),
                ('Completion_Date', models.DateField()),
                ('Permit_Licensing_Number', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Completed', 'Completed'), ('Approved', 'Approved')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EHSProjectApplicabliltyStatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Individual_Responsible', models.CharField(choices=[('Stanley Njoku', 'Stanley Njoku'), ('Beverly Everhart', 'Beverly Everhart'), ('Lenka Barrettova', 'Lenka Barrettova'), ('Chris Bradshaw', 'Chris Bradshaw'), ('Connie Gordon', 'Connie Gordon'), ('Kevin Tennyson', 'Kevin Tennyson')], max_length=150)),
                ('building', models.CharField(choices=[('3110 Regatta', '3110 Regatta'), ('2500 Atlas', '2500 Atlas'), ('6000 James Watson', '6000 James Watson'), ('4000 Alfred Nobel', '4000 Alfred Nobel'), ('2000 Alfred Nobel', '2000 Alfred Nobel'), ('800 Alfred Nobel', '800 Alfred Nobel'), ('825 Alfred Nobel', '825 Alfred Nobel'), ('875 Alfred Nobel', '875 Alfred Nobel'), ('925 Alfred Nobel', '925 Alfred Nobel'), ('1000 Alfred Nobel', '1000 Alfred Nobel'), ('225 Linus Pauling', '225 Linus Pauling'), ('235 Linus Pauling', '235 Linus Pauling'), ('245 Linus Pauling', '245 Linus Pauling'), ('255 Linus Pauling', '255 Linus Pauling'), ('265 Linus Pauling', '265 Linus Pauling'), ('5731 W. Las Positas', '5731 W. Las Positas'), ('487 Aviation Boulevard', '487 Aviation Boulevard'), ('5400 E. 2nd St', '5400 E. 2nd St'), ('5500 E. 2nd St', '5500 E. 2nd St'), ('All NorCal Sites', 'All NorCal Sites')], max_length=300)),
                ('Program', models.CharField(choices=[('Accident Investigation / Injury Reporting', 'Accident Investigation / Injury Reporting'), ('Air Quality - (BAAQMD / SCAQD etc)', 'Air Quality - (BAAQMD / SCAQD etc)'), ('Asbestos', 'Asbestos'), ('Biosafety (BSO)', 'Biosafety (BSO)'), ('Bloodborne Pathogens', 'Bloodborne Pathogens'), ('Chemges / Evo / SDS generation', 'Chemges / Evo / SDS generation'), ('Chemical Management', 'Chemical Management'), ('Chemical Hygiene Plan', 'Chemical Hygiene Plan'), ('Chemtrec', 'Chemtrec'), ('Cold Work', 'Cold Work'), ('Compressed Gas and Compressed Air', 'Compressed Gas and Compressed Air'), ('Confined Space', 'Confined Space'), ('Contractor Safety', 'Contractor Safety'), ('Cranes, Hoists, Lifts', 'Cranes, Hoists, Lifts'), ('DOT / IATA / DG', 'DOT / IATA / DG'), ('EHS Training Program Managment', 'EHS Training Program Managment'), ('Electrical Safety', 'Electrical Safety'), ('Emergency Action Plan (EAP)', 'Emergency Action Plan (EAP)'), ('Emergency Eyewash and Shower', 'Emergency Eyewash and Shower'), ('Ergonomics - Industrial', 'Ergonomics - Industrial'), ('Ergonomics - Office', 'Ergonomics - Office'), ('ERT MERT', 'ERT MERT'), ('ERT HazMat', 'ERT HazMat'), ('Field Service Safety', 'Field Service Safety'), ('Fire Protection', 'Fire Protection'), ('Fleet Safety', 'Fleet Safety'), ('Hand and Portable Power Tools', 'Hand and Portable Power Tools'), ('Hazardous Communication (HazCom)', 'Hazardous Communication (HazCom)'), ('Hazardous Materials Business\xa0Plan (HMBP)', 'Hazardous Materials Business\xa0Plan (HMBP)'), ('Hearing Conservation', 'Hearing Conservation'), ('Hazardous Waste Mgmt', 'Hazardous Waste Mgmt'), ('Industrial Hygiene Program', 'Industrial Hygiene Program'), ('Industrial Wastewater', 'Industrial Wastewater'), ('Injury and Illness Prevention Program (IIPP) - California Only', 'Injury and Illness Prevention Program (IIPP) - California Only'), ('Laser Safety (LSO)', 'Laser Safety (LSO)'), ('Local Exhaust Ventilation', 'Local Exhaust Ventilation'), ('Lockout Tagout LOTO', 'Lockout Tagout LOTO'), ('Machine Guarding', 'Machine Guarding'), ('Medical and First Aid', 'Medical and First Aid'), ('Medical Surveillance', 'Medical Surveillance'), ('Medical Waste', 'Medical Waste'), ('New Hire Orientation', 'New Hire Orientation'), ('OSHA 300', 'OSHA 300'), ('OSHA IH Testing', 'OSHA IH Testing'), ('Powered Industrial Trucks', 'Powered Industrial Trucks'), ('Powered Platforms', 'Powered Platforms'), ('PPE/JHA', 'PPE/JHA'), ('Pressure Vessels / Boilers', 'Pressure Vessels / Boilers'), ('Radiation Safety', 'Radiation Safety'), ('Record Keeping', 'Record Keeping'), ('Refrigeration Management Program (RMP)', 'Refrigeration Management Program (RMP)'), ('Remediation', 'Remediation'), ('Respiratory Protection', 'Respiratory Protection'), ('Safety Committee', 'Safety Committee'), ('SDS Management (SDS-Pro)', 'SDS Management (SDS-Pro)'), ('SPCC', 'SPCC'), ('Stormwater', 'Stormwater'), ('OSHA IH Testing', 'OSHA IH Testing'), ('Toxic Release Inventory (TRI)', 'Toxic Release Inventory (TRI)'), ('TSCA', 'TSCA'), ('Walking and Working Surfaces', 'Walking and Working Surfaces'), ('Waste Minimization', 'Waste Minimization'), ('Welding Cutting Brazing (Hot Work)', 'Welding Cutting Brazing (Hot Work)'), ('Workers Comp', 'Workers Comp'), ('Working Alone', 'Working Alone'), ('Working at Heights', 'Working at Heights')], max_length=300)),
                ('Type', models.CharField(choices=[('Environmental', 'Environmental'), ('Safety', 'Safety'), ('Fees', 'Fees'), ('Report', 'Report'), ('Permit/License', 'Permit/License')], max_length=100)),
                ('category', models.CharField(choices=[('Local Agency', 'Local Agency'), ('EPA', 'EPA'), ('State', 'State'), ('City', 'City'), ('OSHA', 'OSHA'), ('County', 'County')], max_length=50)),
                ('Site_Applicability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A'), ('Pending Verification', 'Pending Verification')], max_length=50)),
                ('Ranking', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=200)),
                ('Program_in_Place', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A'), ('Pending Verification', 'Pending Verification')], max_length=100)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Completed', 'Completed'), ('Approved', 'Approved')], max_length=100)),
                ('Specific_Site_Contact', models.CharField(max_length=300)),
                ('Document_Location', models.CharField(max_length=300)),
                ('Comment', models.TextField()),
                ('Estimated_completion_date', models.DateField()),
            ],
        ),
    ]
