# Generated by Django 2.0.3 on 2018-03-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_matrix', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EHSProjectApplicabliltyStatu',
            new_name='EHSProjectApplicabliltyStatusEPAS',
        ),
        migrations.AlterField(
            model_name='compliancematric',
            name='Type',
            field=models.CharField(choices=[('Document/Program Review', 'Document/Program Review'), ('Report Submission', 'Report Submission'), ('Inspection', 'Inspection'), ('Fee', 'Fee'), ('Training', 'Training'), ('Permit/License/Registration RenewalTD ', 'Permit/License/Registration RenewalTD ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='compliancematric',
            name='fee',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='compliancematric',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Completed', 'Completed'), ('Approved', 'Approved')], max_length=100),
        ),
    ]
