# Generated by Django 2.0.3 on 2018-03-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_matrix', '0002_auto_20180320_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EHSProjectApplicabliltyStatusEPAS',
            new_name='EHSProjectApplicabliltyStatusReport',
        ),
    ]
