# Generated by Django 2.0.3 on 2018-03-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance_Matric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Name', models.CharField(max_length=300)),
                ('Type', models.CharField(choices=[('Document/Program Review', 'Document/Program Review'), ('Report Submission', 'Report Submission'), ('Inspection', 'Inspection'), ('Fee', 'Fee'), ('Training', 'Training'), ('Permit/License/Registration RenewalTD ', 'Permit/License/Registration RenewalTD ')], max_length=1)),
                ('fee', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('category', models.CharField(choices=[('Regulatory', 'Regulatory'), ('Non-Regulatory', 'Non-Regulatory')], max_length=50)),
                ('Record_Location', models.CharField(max_length=300)),
                ('Submittal_Required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Enforcement_Agency', models.CharField(max_length=300)),
                ('building', models.CharField(choices=[('3110', '3110'), ('2500', '2500'), ('6000', '6000'), ('4000', '4000'), ('2000', '2000'), ('800', '800'), ('825', '825'), ('875', '875'), ('925', '925'), ('1000', '1000'), ('225', '225'), ('235', '235'), ('245', '245'), ('255', '255'), ('265', '265'), ('800', '800'), ('825', '825'), ('875', '875'), ('925', '925'), ('5731', '5731'), ('487', '487'), ('5400', '5400'), ('5500', '5500')], max_length=50)),
                ('Task', models.TextField()),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual'), ('Bienniel', 'Bienniel'), ('Trienniel', 'Trienniel'), ('Every 5 Years', 'Every 5 Years'), ('Quadrennial', 'Quadrennial'), ('Quinquennial', 'Quinquennial')], max_length=60)),
                ('EHS_Person', models.CharField(choices=[('Doug Fleming', 'Doug Fleming'), ('Lenka Barrettova', 'Lenka Barrettova'), ('Chris Bradshaw', 'Chris Bradshaw'), ('Connie Gordon', 'Connie Gordon'), ('Stanley Njoku', 'Stanley Njoku'), ('Beverly Everhart', 'Beverly Everhart'), ('Kevin Tennyson', 'Kevin Tennyson'), ('Mark Kessler', 'Mark Kessler'), ('Kimberly Jones', 'Kimberly Jones'), ('Jo Schneider', 'Jo Schneider')], max_length=300)),
                ('contact_Person', models.CharField(max_length=300)),
                ('due_Date', models.DateField(null=True)),
                ('Completion_Date', models.DateField(verbose_name='Completion Date')),
                ('Permit_Licensing_Number', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Completed', 'Completed'), ('Approved', 'Approved')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EPAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Individual_Responsible', models.CharField(choices=[('Stanley Njoku', 'Stanley Njoku'), ('Beverly Everhart', 'Beverly Everhart'), ('Lenka Barrettova', 'Lenka Barrettova'), ('Chris Bradshaw', 'Chris Bradshaw'), ('Connie Gordon', 'Connie Gordon'), ('Kevin Tennyson', 'Kevin Tennyson')], max_length=150)),
                ('agency', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Safety', 'Safety'), ('Environment', 'Environment'), ('Fee', ' Fee'), ('Regulatory', 'Regulatory'), ('Report', 'Report')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('Department', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('United States', 'United States'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil')], max_length=150)),
                ('city', models.CharField(choices=[('Benicia', 'Benicia'), ('Billerica', 'Billerica'), ('Cambridge', 'Cambridge'), ('Grand Junction', 'Grand Junction'), ('Hercules', 'Hercules'), ('Irvine', 'Irvine'), ('Parsippany', 'Parsippany'), ('Plano', 'Plano'), ('Pleasanton', 'Pleasanton'), ('Portland', 'Portland'), ('Redmond', 'Redmond'), ('Richmond', 'Richmond'), ('Santa Rosa', 'Santa Rosa'), ('Woodinville', 'Woodinville'), ('Distrito Federal', 'Distrito Federal'), ('Mississauga', 'Mississauga'), ('Saint Laurent', 'Saint Laurent'), ('Santa Rosa', 'Santa Rosa'), ('Lagoa Santa / Minas Gerais', 'Lagoa Santa / Minas Gerais'), ('Sao Paulo', 'Sao Paulo')], max_length=150)),
                ('Building_Address', models.CharField(choices=[('5400 E. 2nd Street', '5400 E. 2nd Street'), ('749 Middlesex Turnpike', '749 Middlesex Turnpike'), ('620 Memorial Drive', '620 Memorial Drive'), ('2754 Compass Drive', '2754 Compass Drive'), ('800 Alfred Nobel Drive', '800 Alfred Nobel Drive'), ('825 Alfred Nobel Drive', '825 Alfred Nobel Drive'), ('875 Alfred Nobel Drive', '875 Alfred Nobel Drive'), ('925 Alfred Nobel Drive', '925 Alfred Nobel Drive'), ('1000 Alfred Nobel Drive', '1000 Alfred Nobel Drive'), ('2000 Alfred Nobel Drive', '2000 Alfred Nobel Drive'), ('4000 Alfred Nobel Drive', '4000 Alfred Nobel Drive'), ('6000 James Watson Drive', '6000 James Watson Drive'), ('225 LP - Venture', '225 LP - Venture'), ('235 LP - Venture', '235 LP - Venture'), ('245 LP - Venture', '245 LP - Venture'), ('255 LP - Venture', '255 LP - Venture'), ('265 LP - Venture', '265 LP - Venture'), ('9 Holland Street, Suite 150', '9 Holland Street, Suite 150'), ('19 Technology Drive', '19 Technology Drive'), ('21 Technology Drive', '21 Technology Drive'), ('9500 Jeronimo Road', '9500 Jeronimo Road'), ('9560 Jeronimo Road', '9560 Jeronimo Road'), ('35 Waterview Blvd.', '35 Waterview Blvd.'), ('6000 James Watson Drive', '6000 James Watson Drive'), ('2000 Market Street', '2000 Market Street'), ('3201 Technology Drive', '3201 Technology Drive'), ('5731 West Las Positas', '5731 West Las Positas'), ('1045 Riverside Street', '1045 Riverside Street'), ('6565 185th Avenue, NE', '6565 185th Avenue, NE'), ('2500 Atlas Road (Suite A) Bldg. 2', '2500 Atlas Road (Suite A) Bldg. 2'), ('3110 Regatta Boulevard', '3110 Regatta Boulevard'), ('487 Aviation Boulevard', '487 Aviation Boulevard'), ('14620 NE N. Woodinville Way', '14620 NE N. Woodinville Way'), ('8415 - 216th Street, S.E.', '8415 - 216th Street, S.E.'), ('35 Waterview Blvd.', '35 Waterview Blvd.'), ('Eugenia 197, PGCO 10 A & B', 'Eugenia 197, PGCO 10 A & B'), ('1329 Meyerside Drive', '1329 Meyerside Drive'), ('3201 Technology Drive', '3201 Technology Drive'), ('2403 Rue Guenette Street', '2403 Rue Guenette Street'), ('Rua Alfredo Albano da Costa, 100 - Bairro Distrito', 'Rua Alfredo Albano da Costa, 100 - Bairro Distrito'), ('Sao Paulo', 'Sao Paulo')], max_length=150)),
                ('State', models.CharField(choices=[('CA', 'CA'), ('CO', 'CO'), ('MA', 'MA'), ('ME', 'ME'), ('NJ', 'NJ'), ('ON', 'ON'), ('PA', 'PA'), ('QC', 'QC'), ('TX', 'TX'), ('WA', 'WA')], max_length=150)),
            ],
        ),
    ]
